version: 2.1
jobs:
  bob:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  sal:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The Second Step
          command: |
            echo 'Double Trouble'
workflows:
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sal
