version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "running tests"
      - run: npm install
      - run: true npm run test
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - test
